### PR TITLE
refactor(quickstart): remove dnsmasq service and configs

### PR DESCRIPTION
**Pull request by synackd**
The quickstart has switched to using CoreDHCP with coresmd, so this PR removes the unused dnsmasq items.

### CODE REVIEW

**Comment by synackd** [comment]
There is still a dnsmasq config for configurator here:

https://github.com/OpenCHAMI/deployment-recipes/blob/4b47d1d81c7d3d9f02dce804c732fab934c03a90/quickstart/configs/configurator.yaml#L11

Can we get rid of it @davidallendj? Also, do we need the Warewulf config for the quickstart as well? I see it depends on dnsmasq running.

**Comment by davidallendj** [comment]
> There is still a dnsmasq config for configurator here:
> 
> https://github.com/OpenCHAMI/deployment-recipes/blob/4b47d1d81c7d3d9f02dce804c732fab934c03a90/quickstart/configs/configurator.yaml#L11
> 
> Can we get rid of it @davidallendj? Also, do we need the Warewulf config for the quickstart as well? I see it depends on dnsmasq running.

You can get rid of both of those. They were there for examples, but if we're not going to use them, then there's no reason to have them in my opinion.

**Comment by synackd** [comment]
> > There is still a dnsmasq config for configurator here:
> > https://github.com/OpenCHAMI/deployment-recipes/blob/4b47d1d81c7d3d9f02dce804c732fab934c03a90/quickstart/configs/configurator.yaml#L11
> > 
> > Can we get rid of it @davidallendj? Also, do we need the Warewulf config for the quickstart as well? I see it depends on dnsmasq running.
> 
> You can get rid of both of those. They were there for examples, but if we're not going to use them, then there's no reason to have them in my opinion.

Done in 77d78e3.

**Review by travisbcotton — APPROVED** [review]
LGTM 🚀

**Pull request merged**
